language: node_js
node_js:
  - "10.4"

before_install:
  - sudo apt-get update

install:

  - cd /home/travis/build/ilovecatherine/msa-recap-ffmpeg-container
  - sudo apt-get install azure-cli
  - az login -u $USERNAME -p $PASSWORD
  - sudo apt-get install azure-functions-core-tools-3


deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch:
  on:
    branch: master
